FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/{{ .Slug }} ./cmd/server

FROM alpine:3.19
COPY --from=build /bin/{{ .Slug }} /usr/local/bin/{{ .Slug }}
EXPOSE 8080
ENTRYPOINT ["{{ .Slug }}"]
